name: Build Salesforcex

on:
  workflow_dispatch: { }
  pull_request: { }
  push: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: npm ci
      - run: npm run build

  